:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 15
development:
  :concurrency: 1
:queues:
  - default
  - mailers

:schedule:
  comments_check:
    cron: '0 * * * * *'   # Runs once per minute
    class: CheckNotifiableCommentsRunner
